# Generated by Django 2.2.3 on 2019-08-05 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20190805_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=16)),
                ('u_icon', models.ImageField(upload_to='%Y/%m/%d/static')),
            ],
        ),
    ]
