# Generated by Django 2.2.3 on 2019-08-02 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_name', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=32, unique=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('s_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Grade')),
            ],
        ),
        migrations.CreateModel(
            name='StuInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_hobby', models.CharField(default='gaming', max_length=16)),
                ('i_age', models.IntegerField(default=18)),
                ('i_birth', models.DateTimeField(auto_now_add=True)),
                ('i_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Student')),
            ],
        ),
    ]
