# Generated by Django 2.2.3 on 2019-08-04 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=16)),
                ('u_password', models.CharField(max_length=128)),
                ('u_token', models.CharField(max_length=128)),
            ],
        ),
    ]
